/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';
import { getData } from 'react-native-cognito-asf-fingerprint';
import base64 from 'react-native-base64'

export default class App extends Component<{}> {
  state = {
    status: 'ready',
    aSFDeviceId: '--',
    signature: '--',
    version: '--',

  };

  requestFingerprint = async () => {
    const message = await getData('userid', 'poolId', 'clientId')
    // message will base64 encoded JSON blob
    const decoded = base64.decode(message);
    const {payload, version, signature} = JSON.parse(decoded);
    const parsedPayload = JSON.parse(payload);

    this.setState({
      status: 'device fingerprint received', 
      signature,
      version,
      aSFDeviceId: parsedPayload.contextData.DeviceId,
      payload,
      custom: parsedPayload.contextData.DeviceFingerprint,
      message
    });

  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>CognitoAsfFingerprint example</Text>
        <Button title="Get ASF Fingerprint" onPress={this.requestFingerprint} />
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>Fingerprint</Text>
        <Text style={styles.instructions}>Signature: {this.state.signature}</Text>
        <Text style={styles.instructions}>Version: {this.state.version}</Text>
        <Text style={styles.instructions}>ASF DeviceId: {this.state.aSFDeviceId}</Text>
        <Text style={styles.instructions}>$${this.state.message}$$</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});


