require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

platform :ios, '10.0'

target 'demo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # aws-amplify-ios seems to only work with use_frameworks
  pod 'AWSCognitoIdentityProviderASF', :build_type => :dynamic_framework

  target 'demoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'demo-tvOS' do
  # Pods for demo-tvOS

  target 'demo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
